### ISSUE TITLE
Create CA button doesn't seem to do anything

### ISSUE THREAD

**Issue by jp83** [Division42LLC/division42llc-dotnet-webca#2]
I like this idea for my homelab, and have tried running via docker:

```
docker run -d --name=webca \
  --net=traefik-net \
  --restart=always \
  --memory=40m \
  division42llc/dotnet-webca

# initially was worried about permissions and disk space issues
#  -u=1009 \
#  -v $PWD/localCA:/var/localCA \

```

I goto the page to create the initial CA and fill in all the fields.  The "+ Create CA" button highlights green, it spins for about 10 sec, and then just returns back to the populated form with no message or indication that it's done anything.  Clicking around, I confirmed it hasn't done anything.

Not sure how/where to debug or find additional logs, but I did try looking in /var/log via console.

**Comment by RobSeder** [comment]
This doesn't seem to be complete because you are also not exposing any ports. Can you try running this, instead (from the main readme)?

On Linux or macOS:
```
$ docker run -d -p 8080:8080 -v ~/Desktop/localCA/:/var/localCA/ --memory=40m division42llc/dotnet-webca
```
On Windows:
```
$ docker run -d -p 8080:8080 -v %UserProfile%/Desktop/localCA/:/var/localCA/ --memory=40m division42llc/dotnet-webca
```
As far as troubleshooting - this is an AngularJS front-end which just hits REST endpoints. So, you can hit F12 in most browsers to open the "developer tools" and switch to the "Console" view. If there are errors, they will show up there.

As far running as root - I pushed out a new version last week where this container now runs as a non-privileged user. Let me know how this goes?

**Comment by jp83** [comment]
I'm using traefik which is automatically picking up the only exposed port 8080 and doing reverse proxy to it from the container name.  I can get to the page no problem.  But inspecting console I do see 502 errors:

```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
/api/ca/get
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
angular.js:11821 POST http://webca.docker.xxx.com/api/ca/create 502 (Bad Gateway)
```

I just re-pulled the image again earlier today before submitting, so I should have the latest.

Port 8080 is already used on the machine, trying to map to a different one created more problems, the page loaded, but I couldn't even click on the button on the first page and had more 502 Bad Gateway messages.

Googling suggests it's a "server side" issue, but probably  due to my config.  Is node.js serving the page/response directly, or another server that may have an issue with the hostname/port it expects to receive in the header?

**Comment by RobSeder** [comment]
Sounds like kind of a complicated setup. How I would assume you would do that is with a docker-compose.yml file and "link" the various servers so that they can talk to each other by name.

To answer your question though - this is a .NET Core application and I believe it binds to 0.0.0.0:80 - which means it should be listening for requests on the one IP of that container. The AngularJS calls make a relative call - so URL's like "/api/something" - meaning "on the same server and port, but just in this other directory".

I don't know why you are seeing a problem. If you can navigate to / to get the first index.html, then other calls to /api/* should just be more of the same. The only other thought I have is that since this is an AngularJS app - it likes to cache web pages. You may be looking at a cached page where in real life, the actual website is also not loading. Try doing a CTRL+R (Command+R on Mac) in your browser to refresh the page withOUT using browser cache. Does the site still work? You are navigating to it on your local machine as http://localhost:8080/ correct? Except that is really talking to your reverse proxy, and then your reverse proxy talks to this web app?

**Comment by johnf** [comment]
I had this issue and it was related to the permissions of /var/localCA not being writeable.
Only works if it is owned by uid 1001 which is user everything runs as

**Comment by SloCompTech** [comment]
Yup, permission problems,
```
     _ _       _     _             _  _  ____  _ _         __  _       _              _                    _
  __| (_)_   _(_)___(_) ___  _ __ | || ||___ \| | | ___   / /_| | ___ | |_ _ __   ___| |_    __      _____| |__   ___ __ _
 / _` | \ \ / / / __| |/ _ \| '_ \| || |_ __) | | |/ __| / / _` |/ _ \| __| '_ \ / _ \ __|___\ \ /\ / / _ \ '_ \ / __/ _` |
| (_| | |\ V /| \__ \ | (_) | | | |__   _/ __/| | | (__ / / (_| | (_) | |_| | | |  __/ ||_____\ V  V /  __/ |_) | (_| (_| |
 \__,_|_| \_/ |_|___/_|\___/|_| |_|  |_||_____|_|_|\___/_/ \__,_|\___/ \__|_| |_|\___|\__|     \_/\_/ \___|_.__/ \___\__,_|


        Image Name............: division42llc/dotnet-webca
        Image Version.........: ��0.6.2
        Image Built...........: Wed Oct 10 17:49:59 UTC 2018
        Help URL..............: https://github.com/Division42LLC/division42llc-dotnet-webca


------ Environment ------ \/\/\/\/\/\/\/
ASPNETCORE_URLS=http://+:80
DOTNET_SDK_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.1.11/dotnet-dev-debian-x64.1.1.11.tar.gz
DOTNET_SDK_VERSION=1.1.11
HOME=/
HOSTNAME=12b245095df0
IMAGE_BUILT=Wed Oct 10 17:49:59 UTC 2018
IMAGE_NAME=division42llc/dotnet-webca
IMAGE_VERSION=��0.6.2
NODE_DOWNLOAD_SHA=467472d9adafd067588f2a20f9edcd7493d973fe107502c55d6fabfa0d3f91af
NODE_DOWNLOAD_URL=https://nodejs.org/dist/v6.13.0/node-v6.13.0-linux-x64.tar.gz
NODE_VERSION=6.13.0
NUGET_XMLDOC_MODE=skip
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/app
SHLVL=1
_=/usr/bin/env
------ Environment ------ /\/\/\/\/\/\/\

.NET Command Line Tools (1.1.11)

Product Information:
 Version:            1.1.11
 Commit SHA-1 hash:  d2610b5786

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.1.11

Hosting environment: Production
Content root path: /app
Now listening on: http://0.0.0.0:8080
Application started. Press Ctrl+C to shut down.
GET /api/ca/get
POST /api/ca/create
PFX/PKCS12: Access to the path '/var/localCA/CA/ca-cert.pfx' is denied.
GET /api/ca/get
```

**Comment by RobSeder** [comment]
Just an update. If it's just the permissions, I updated the `Dockerfile` to do a:

```bash
chmod 777 /var/localCA
```

which I assume would resolve this.

You can go `git pull` the latest, or I just re-setup the Git hooks to build to the Docker Store. It's v-e-r-y slow, but the next `:latest` and `0.6.4` tag in the Docker Store should be this change.

**Comment by SloCompTech** [comment]
Hello,
now it is working, if you use bind volume, you need to make sure for correct permission, if you use volume, than it works out of the box

**Comment by RobSeder** [comment]
@SloCompTech Great to hear! And things seem to check out for me to. Let me know if you have other issues - I apologize for the delays.

**Comment by BillMeyerRSA** [comment]
Version 0.6.11
Access to the path '/var/localCA/CA' is denied.
Seems like same problem reported 
`------ Environment ------ /\/\/\/\/\/\/\ 

.NET Command Line Tools (1.1.14)

Product Information:
 Version:            1.1.14
 Commit SHA-1 hash:  c2e899a453

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.1.14

Hosting environment: Production
Content root path: /app
Now listening on: http://0.0.0.0:8080
Application started. Press Ctrl+C to shut down.
GET /api/ca/get
POST /api/ca/create
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLSKAH10GOI6": An unhandled exception was thrown by the application.
System.UnauthorizedAccessException: Access to the path '/var/localCA/CA' is denied. ---> System.IO.IOException: Permission denied
`

**Comment by BillMeyerRSA** [comment]
Changed the permissions in the Host on directory /home/<hostname>/Desktop/localCA to 777 and now it is working.
Platform is Docker on Ubuntu Server
