### ISSUE TITLE
CA / Leaf Expirations

### ISSUE THREAD

**Issue by carpenike** [Division42LLC/division42llc-dotnet-webca#6]
Unless I missed something it looks like the service defaults at 2 years for an expiration? Is this customizable in some way?

**Comment by RobSeder** [comment]
@carpenike,

I don't have any time at all to work on this. Please - update:

> **https://github.com/Division42LLC/division42llc-dotnet-webca/blob/master/src/Division42LLC.WebCA/x509/CertificateGenerator.cs#L146**

and do a pull request. Perhaps default it to 20 years?

-Rob

**Comment by RobSeder** [comment]
@carpenike Sorry for the delay. I did modify this and create release `0.6.5`. I changed the default certificate expiration from 2 years, to 20 years. If you want longer, or want to make it configurable, please do a pull request. Otherwise, version `0.6.5` (or `:latest` on Docker Store) will default to 20 years. Thanks
